# Change these first
owner: urban-sustainability-lab-zurich # Your GitHub organization or username, where this repository lives
repo: susdis_monitor # The name of this repository

sites:
  - name: Main project website
    url: https://sustainability.discourses.ch
  - name: Sustainbility Discourse Map (Zürich)
    url: https://zuerich.sustainability.discourses.ch
  - name: Sustainbility Discourse Map (Zürich), Example query topic (parking)
    url: https://zuerich.sustainability.discourses.ch/topic/PRK

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /susdis_monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: sustainability.discourses monitor
  introTitle: "sustainability.discourses uptime monitor and status page"
  introMessage: "This is a status monitoring page for web resources of the sustainability.discourses project"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
